[project]
name = "screen-scanner"
version = "0.1.0"
description = "Scans the screen and renders bounding box on top of recognized objects."
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0",
    "ultralytics==8.4.174",
    "pillow==12.3.0"
]

[project.optional-dependencies]
cpu = [
    "torch==2.14.1",
]
gpu = [
    "torch==2.14.1+cu126",
]